---
:api_key: dc91636725415f837b2d62bf742484cc
:password: 68ec9b2609a71f0a50ea230eafa0eb6d
:store: juno-mohawk.myshopify.com
:theme_id: 
:whitelist_files:
- layout/
- assets/
- config/
- snippets/
- templates/
- locales/
